- hosts: localhost
  vars_files:
          var.yml
  tasks:
    - name: ec2 instance
      ec2:
              region: "{{region}}"
              image: ami-08f63db601b82ff5f
              instance_type: t2.micro
              group_id: sg-08fbfbe721c8b99db
              key_name: aws2
              count: 1
              instance_tags:
                      name: loadbalancer
              state: present
              vpc_subnet_id: subnet-3d323b55
              aws_access_key: "{{aws_access}}"
              aws_secret_key: "{{aws_secret}}"
    - name: ec2
      ec2:
               region: "{{region}}"
               image:  ami-08f63db601b82ff5f
               instance_type: t2.micro
               group_id: sg-08fbfbe721c8b99db
               key_name: aws2
               count: 2
               instance_tags:
                        name: web_server
               state: present
               vpc_subnet_id: subnet-3d323b55
               aws_access_key: "{{aws_access}}"
               aws_secret_key: "{{aws_secret}}"
    
                   
